services:
  web-fuzzer:
    build: .
    image: web-fuzzer:latest
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY:-default-secret-key}
      - FLASK_ENV=production
      - FLASK_APP=app.py
      - FLASK_DEBUG=0
    volumes:
      - ./wordlists:/app/wordlists
      - ./results:/app/results
      - ./uploads:/app/uploads
      - ./config:/app/config
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M
