name: Deploy Web Fuzzer to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.60.182.109 << 'EOF'
            cd ~/projects/Web-Fuzzer || git clone https://github.com/raulskat/Web-Fuzzer.git ~/projects/Web-Fuzzer
            cd ~/projects/Web-Fuzzer
            git pull origin main
            docker-compose down
            docker-compose up -d --build
          EOF
